---
title: 
  "Investigating the efficacy of consumer interventions on sales of zero-calorie beverages"
format: 
  pdf:
    fontsize: 11pt
date:
  2024-03-01
editor: 
  visual
bibliography: 
  ../docs/references.bib
csl: 
  ../docs/elsevier-vancouver.csl
author: 
- Christine Chuong (20124798)
- Giuliano Cruz (79247979)
- Joey Hotz (18461400)
include-in-header: 
  text: |
    \usepackage{authblk}
    \pagenumbering{gobble}
---

{{< pagebreak >}}

\pagenumbering{arabic}

# Introduction

Strong evidence has linked habitual intake of sugar-sweetened beverages (SSBs) with weight gain and a higher risk of type 2 diabetes mellitus, cardiovascular diseases, and even cancer @Malik2022. Multiple policy interventions to inhibit consumption of SSBs have been proposed @Krieger2021, including taxation of SSBs, limiting access to SSBs in schools and healthcare facilities, and adding informative package labelling. As policymakers create potential interventions to limit SSB consumption, there is a need for data-driven methods of determining their efficacy.

This study aims to evaluate two kinds of interventions which intend to shift consumers towards zero-calorie beverages: interventions with caloric messaging or price discounts. There are three caloric messaging interventions and two price discount interventions.

The primary statistical question is whether these interventions are associated with differences in the average proportion of daily sales of zero-calorie beverages. Secondary questions include whether there are significant interactions between interventions and site effects, and whether a combination of interventions are more effective than each individual intervention.

# Data Description and Summaries

The data come from an interrupted time-series multi-site quasi-experimental study on sales of sweetened and zero-calorie beverages at three United States hospitals over a 30-week period. There are 631 observations across all three sites. Each observation represents the total daily sales of bottled beverages across multiple storefronts at a single site. Sales are recorded automatically by point of sale terminals in Site A, and manually by cashiers at Sites B and C. Sales are recorded every day from the start of the experiment until the final day, including weekends and holidays.

The data includes the following variables: the day of the experiment, the corresponding weekday, the site, and the ongoing intervention. The day variable is a positive integer. Categorical variables include weekday with seven levels, site with three levels, and intervention with nine levels. The daily sales metrics include the number of bottled zero-calorie and sweetened beverages sold per site. These are each non-negative integer variables. The data also includes the total number of beverages sold per site, which is another non-negative integer value.

Some observations include the sales of 100% juice, orange juice, and sports drinks, which are recorded as integers. These counts are only consistently recorded at Site A, and rarely recorded for Site B and C. There are nine days which are missing counts for the bottled zero-calorie and sugared beverages. Counts for the bottles zero-calorie and sugared beverages are missing in nine observations, each containing missing data for every sales-related column. Of these nine observations, seven occur in the final week of the study at Site B, and two occur mid-study at Site C.

# Exploratory Analysis

Side-by-side boxplots of the proportion of total sales coming from zero-calorie drinks for each site for each day of the week were created. They showed a similar proportion for each site and day of the week across sites, though one of the sites differed slightly and seemed to have more variable sales. Boxplots of total drinks sold showed one site had a lot more sales than the other two sites. Sales were also much lower for all sites on weekends compared to weekdays

A plot of the proportion of total sales coming from zero-calorie drinks over experiment day (@fig-1), shows the trends of sales across each site over day. There was some difference at the beginning of the experiment, but over time the average proportion seemed relatively stable, which is not expected.A scatterplot matrix comparing sugary, zero-calorie and total drink sales showed that they are all highly correlated with each other. The matrix also shows a positive linear relationship between zero-calorie, sugary and total sales.

A missing data plot showed that orange juice, 100% juice and sports drinks had many missing observations. A missing data table also showed many missing juice or sport drink sales, additionally showing that some sites did not record some of these sales at all. Since juice and sport drink sales are not of interest, and are inconsistently recorded, they are not included in the analysis. The missing data plot also showed nine observations had no sale measurements, which are also omitted. 

```{r,echo=FALSE,message=FALSE,warning=FALSE}
#| label: fig-1
#| fig-cap: Proportion of total sales coming from zero-calorie drinks over time

library(here) 
library(tidyverse)

# Read in data
sugary_bev <- read.csv(file = "../rawdata/june1data.csv", 
  colClasses = c("DofW" = "factor", "Site" = "factor", "Intervention" = "factor"))

# Get rid of rows with total sales less than the drink sales summed and missing totals
sugary_bev$totals <-rowSums(sugary_bev[,5:9],na.rm = T)
sugary_bev =sugary_bev[!is.na(sugary_bev$Total),]
sugary_bev = sugary_bev[!(sugary_bev$Total<sugary_bev$totals),]

sugary_bev %>%
  mutate(percent_zero = ZeroCal/Total) %>%
  ggplot(aes(x=Count,y=percent_zero,col=Site))+
  geom_point(alpha=0.5)+
  geom_smooth(se=F)+
  scale_fill_continuous(guide = guide_legend()) +
  theme(legend.position="bottom")+
  theme_minimal()+
  labs(x = "Day of the Experiment",
       y = "Proportion of Total Sales") 
```

# Formal Analysis

In this study, an effective intervention will increase, relative to the baseline, the proportion of daily sales of zero-calorie beverages among sales that are either zero-calorie beverages or sugary beverages. This proportion increases when there are relatively more sales of zero-calorie beverages than of sugary beverages. This avoids the need to perform two separate analyses (one for zero-calorie and another one for sugary beverages) and any variation due to sales of other unrelated products.

To answer the statistical questions, we recommend using a generalized linear mixed effects model (GLMM) with a Poisson distribution. This type of model uses count data and allows for different effects across sites. It can also handle the longitudinal nature of the data. The response variable is the counts of zero-calorie beverage sales. Including the log-transformed total sales of zero-calorie or sugary beverages as an offset, the Poisson GLMM models the proportion of zero-calorie beverage sales as defined previously. The main independent variables of interest are intervention indicators, treating the baseline periods as the reference. Other covariates in the model include the site, the day of the week, and the study day.

To assess whether intervention effects differ by site, we recommend testing interaction effects between sites and intervention groups. This assessment can be implemented as a Likelihood Ratio Test. We recommend including random effects for intervention groups, which would allow for different effects between groups.

A major assumption of the GLMM with Poisson model is the correct specification of the Poisson distribution. To avoid this assumption, a robust version of the above model is recommended. In particular, the same model specification can be used, while employing Poisson estimating equations with a so-called sandwich covariance estimator. This model is known as robust Poisson as it remains valid even if the data do not support a Poisson distribution @Talbot2022. Once exponentiated, coefficients from the GLMM and the robust Poisson model have the same interpretation. For instance, if the exponentiated coefficient for a given intervention is equal to 1.5, then the proportion of zero-calorie beverage sales increases by 50% under the intervention, as compared to the baseline.

# Conclusion

To accurately assess the efficacy of the interventions, it is best to create a statistical model which explains how these interventions affect the proportion of zero-calorie beverages. This response variable is less prone to variation than the overall sales of zero-calorie drinks, and it still provides an easily-interpretable metric for consumer purchasing behaviours.

Therefore, we recommend fitting a Poisson GLMM to the log-transformed sales to predict the proportion of zero-calorie beverage sales, and determining which effects are most relevant using the likelihood ratio test. However, the Poisson GLMM assumes that the underlying data follows a Poisson distribution. If this assumption is not met, we recommend utilizing robust Poisson regression, as the robust Poisson model does not require this distributional assumption. Both analyses employ the zero-calorie beverage sales as the primary outcome with the log of the sum of zero-calorie beverage sales and sugary beverage sales as an offset.

{{< pagebreak >}}

# References

::: {#refs}
:::

{{< pagebreak >}}

# Statistical Appendix


